
spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: say1890
    password: dPQMsdnflwngiddl
    properties:
     mail.smtp.auth: true
     mail.smtp.ssl.enable: true
    


  datasource-mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/mbting?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    
    
  datasource-mongodb:
    driver-class-name:  mongodb.jdbc.MongoDriver   
    host: localhost
    port: 27017
    database: chatdb  
  
  
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp       

     