spring:
  mail:
    host: smtp.naver.com
    port: 465
    username: say1890@naver.com
    password: 2019662002!
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
    


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mbting?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp